name: z_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0-dev.19
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  uuid: ^3.0.6
  rxdart: ^0.27.3
  http: ^0.13.3
  dartz: ^0.10.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.1
