name: z_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0-dev.28
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  uuid: ^3.0.6
  rxdart: ^0.27.3
  http: ^1.1.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.4
